const TODAY = new Date().toISOString().split('T')[0];

function daysFromToday(n) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
}

export const mockMatches = {
  matches: [
    // Live today
    {
      id: 1001,
      status: 'L',
      published: true,
      league_name: 'Southern Premier League',
      league_division_name: 'Division 1',
      competition_type: 'League',
      home_team_id: 54532,
      home_team_name: 'Sparsholt CC 1st XI',
      home_club_name: 'Sparsholt CC',
      away_team_id: 22001,
      away_team_name: 'Andover CC 1st XI',
      away_club_name: 'Andover CC',
      ground_name: 'Sparsholt Village Ground',
      ground_town: 'Sparsholt',
      ground_county: 'Hampshire',
      match_date: TODAY,
      match_time: '11:00',
      result_description: '',
      toss_won_by_team_id: 22001,
      batted_first: 22001,
    },
    // Upcoming fixtures
    {
      id: 1002,
      status: 'P',
      published: true,
      league_name: 'Hampshire Cricket League',
      league_division_name: 'Division 2',
      competition_type: 'League',
      home_team_id: 54533,
      home_team_name: 'Sparsholt CC 2nd XI',
      home_club_name: 'Sparsholt CC',
      away_team_id: 22002,
      away_team_name: 'Romsey CC 2nd XI',
      away_club_name: 'Romsey CC',
      ground_name: 'Sparsholt Village Ground',
      ground_town: 'Sparsholt',
      ground_county: 'Hampshire',
      match_date: daysFromToday(7),
      match_time: '13:00',
      result_description: '',
      toss_won_by_team_id: null,
      batted_first: null,
    },
    {
      id: 1003,
      status: 'P',
      published: true,
      league_name: 'Southern Premier League',
      league_division_name: 'Division 1',
      competition_type: 'League',
      home_team_id: 22003,
      home_team_name: 'Basingstoke CC 1st XI',
      home_club_name: 'Basingstoke CC',
      away_team_id: 54532,
      away_team_name: 'Sparsholt CC 1st XI',
      away_club_name: 'Sparsholt CC',
      ground_name: 'Mays Bounty Ground',
      ground_town: 'Basingstoke',
      ground_county: 'Hampshire',
      match_date: daysFromToday(14),
      match_time: '11:00',
      result_description: '',
      toss_won_by_team_id: null,
      batted_first: null,
    },
    {
      id: 1004,
      status: 'P',
      published: true,
      league_name: 'Hampshire Cricket League',
      league_division_name: 'Division 4',
      competition_type: 'League',
      home_team_id: 22004,
      home_team_name: 'Alresford CC 3rd XI',
      home_club_name: 'Alresford CC',
      away_team_id: 54534,
      away_team_name: 'Sparsholt CC 3rd XI',
      away_club_name: 'Sparsholt CC',
      ground_name: 'Alresford Sports Ground',
      ground_town: 'Alresford',
      ground_county: 'Hampshire',
      match_date: daysFromToday(21),
      match_time: '13:00',
      result_description: '',
      toss_won_by_team_id: null,
      batted_first: null,
    },
    {
      id: 1005,
      status: 'P',
      published: true,
      league_name: '',
      league_division_name: '',
      competition_type: 'Friendly',
      home_team_id: 54535,
      home_team_name: 'Sparsholt CC Sunday XI',
      home_club_name: 'Sparsholt CC',
      away_team_id: 22005,
      away_team_name: 'Compton CC',
      away_club_name: 'Compton CC',
      ground_name: 'Sparsholt Village Ground',
      ground_town: 'Sparsholt',
      ground_county: 'Hampshire',
      match_date: daysFromToday(10),
      match_time: '13:00',
      result_description: '',
      toss_won_by_team_id: null,
      batted_first: null,
    },
    // Past results
    {
      id: 1006,
      status: 'C',
      published: true,
      league_name: 'Southern Premier League',
      league_division_name: 'Division 1',
      competition_type: 'League',
      home_team_id: 54532,
      home_team_name: 'Sparsholt CC 1st XI',
      home_club_name: 'Sparsholt CC',
      away_team_id: 22006,
      away_team_name: 'Winchester CC 1st XI',
      away_club_name: 'Winchester CC',
      ground_name: 'Sparsholt Village Ground',
      ground_town: 'Sparsholt',
      ground_county: 'Hampshire',
      match_date: daysFromToday(-7),
      match_time: '11:00',
      result_description: 'Sparsholt CC won by 6 wickets',
      toss_won_by_team_id: 22006,
      batted_first: 22006,
    },
    {
      id: 1007,
      status: 'C',
      published: true,
      league_name: 'Hampshire Cricket League',
      league_division_name: 'Division 2',
      competition_type: 'League',
      home_team_id: 22007,
      home_team_name: 'Eastleigh CC 2nd XI',
      home_club_name: 'Eastleigh CC',
      away_team_id: 54533,
      away_team_name: 'Sparsholt CC 2nd XI',
      away_club_name: 'Sparsholt CC',
      ground_name: 'Eastleigh Park',
      ground_town: 'Eastleigh',
      ground_county: 'Hampshire',
      match_date: daysFromToday(-7),
      match_time: '13:00',
      result_description: 'Eastleigh CC won by 34 runs',
      toss_won_by_team_id: 22007,
      batted_first: 22007,
    },
    {
      id: 1008,
      status: 'C',
      published: true,
      league_name: 'Hampshire Cricket League',
      league_division_name: 'Division 4',
      competition_type: 'League',
      home_team_id: 54534,
      home_team_name: 'Sparsholt CC 3rd XI',
      home_club_name: 'Sparsholt CC',
      away_team_id: 22008,
      away_team_name: 'Otterbourne CC 3rd XI',
      away_club_name: 'Otterbourne CC',
      ground_name: 'Sparsholt Village Ground',
      ground_town: 'Sparsholt',
      ground_county: 'Hampshire',
      match_date: daysFromToday(-14),
      match_time: '13:00',
      result_description: 'Sparsholt CC won by 4 wickets',
      toss_won_by_team_id: 54534,
      batted_first: 22008,
    },
  ],
};

export const mockMatchDetails = {
  // Live match — Andover batted first, Sparsholt in progress
  1001: {
    match_details: [{
      id: 1001,
      status: 'L',
      home_team_name: 'Sparsholt CC 1st XI',
      away_team_name: 'Andover CC 1st XI',
      ground_name: 'Sparsholt Village Ground',
      match_date: TODAY,
      match_time: '11:00',
      result_description: '',
      innings: [
        {
          team_batting_id: 22001,
          team_batting_name: 'Andover CC 1st XI',
          runs: 203,
          wickets: 8,
          overs: '45.0',
          declared: false,
          extras: { b: 4, lb: 6, w: 9, nb: 1, pen: 0, total: 20 },
          bat: [
            { batsman_name: 'R. Holloway', how_out: 'c Nash b Fletcher', runs: 42, balls: 58, fours: 5, sixes: 0 },
            { batsman_name: 'D. Kimber', how_out: 'lbw b Wade', runs: 15, balls: 22, fours: 2, sixes: 0 },
            { batsman_name: 'T. Aldridge', how_out: 'b Fletcher', runs: 61, balls: 74, fours: 7, sixes: 1 },
            { batsman_name: 'M. Prentice', how_out: 'c Gibson b Sutton', runs: 8, balls: 14, fours: 1, sixes: 0 },
            { batsman_name: 'C. Draper', how_out: 'c Hartley b Sutton', runs: 29, balls: 41, fours: 3, sixes: 0 },
            { batsman_name: 'J. Okafor', how_out: 'not out', runs: 33, balls: 38, fours: 4, sixes: 1 },
            { batsman_name: 'P. Snell', how_out: 'run out (Pearce)', runs: 4, balls: 7, fours: 0, sixes: 0 },
            { batsman_name: 'H. Wynne', how_out: 'c & b Cross', runs: 0, balls: 3, fours: 0, sixes: 0 },
            { batsman_name: 'G. Farrow', how_out: 'not out', runs: 7, balls: 11, fours: 1, sixes: 0 },
            { batsman_name: 'B. Tanner', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'S. Marsh', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
          ],
          bowl: [
            { bowler_name: 'S. Fletcher', overs: '9', maidens: 1, runs: 38, wickets: 2, wides: 3, no_balls: 0 },
            { bowler_name: 'C. Wade', overs: '9', maidens: 2, runs: 31, wickets: 1, wides: 1, no_balls: 0 },
            { bowler_name: 'B. Sutton', overs: '9', maidens: 0, runs: 44, wickets: 2, wides: 2, no_balls: 1 },
            { bowler_name: 'D. Cross', overs: '9', maidens: 1, runs: 35, wickets: 1, wides: 2, no_balls: 0 },
            { bowler_name: 'O. Nash', overs: '9', maidens: 0, runs: 55, wickets: 0, wides: 1, no_balls: 0 },
          ],
        },
        {
          team_batting_id: 54532,
          team_batting_name: 'Sparsholt CC 1st XI',
          runs: 142,
          wickets: 4,
          overs: '28.3',
          declared: false,
          extras: { b: 2, lb: 4, w: 6, nb: 0, pen: 0, total: 12 },
          bat: [
            { batsman_name: 'J. Hartley', how_out: 'c Holloway b Marsh', runs: 38, balls: 52, fours: 4, sixes: 0 },
            { batsman_name: 'T. Griffiths', how_out: 'b Tanner', runs: 12, balls: 19, fours: 1, sixes: 0 },
            { batsman_name: 'W. Pearce', how_out: 'c Draper b Wynne', runs: 45, balls: 61, fours: 5, sixes: 1 },
            { batsman_name: 'O. Nash', how_out: 'lbw b Marsh', runs: 19, balls: 28, fours: 2, sixes: 0 },
            { batsman_name: 'M. Gibson', how_out: 'not out', runs: 22, balls: 29, fours: 3, sixes: 0 },
            { batsman_name: 'B. Sutton', how_out: 'not out', runs: 6, balls: 9, fours: 1, sixes: 0 },
            { batsman_name: 'S. Fletcher', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'D. Cross', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'C. Wade', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'H. Frost', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'P. Carter', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
          ],
          bowl: [
            { bowler_name: 'S. Marsh', overs: '8', maidens: 1, runs: 29, wickets: 2, wides: 2, no_balls: 0 },
            { bowler_name: 'B. Tanner', overs: '7', maidens: 0, runs: 33, wickets: 1, wides: 1, no_balls: 0 },
            { bowler_name: 'H. Wynne', overs: '7.3', maidens: 0, runs: 41, wickets: 1, wides: 2, no_balls: 0 },
            { bowler_name: 'G. Farrow', overs: '6', maidens: 1, runs: 27, wickets: 0, wides: 1, no_balls: 0 },
          ],
        },
      ],
    }],
  },
  // Sparsholt 1st XI beat Winchester by 6 wkts
  1006: {
    match_details: [{
      id: 1006,
      status: 'C',
      home_team_name: 'Sparsholt CC 1st XI',
      away_team_name: 'Winchester CC 1st XI',
      ground_name: 'Sparsholt Village Ground',
      match_date: daysFromToday(-7),
      match_time: '11:00',
      result_description: 'Sparsholt CC won by 6 wickets',
      innings: [
        {
          team_batting_id: 22006,
          team_batting_name: 'Winchester CC 1st XI',
          runs: 178,
          wickets: 10,
          overs: '43.2',
          declared: false,
          extras: { b: 3, lb: 5, w: 8, nb: 2, pen: 0, total: 18 },
          bat: [
            { batsman_name: 'A. Powell', how_out: 'c Gibson b Fletcher', runs: 34, balls: 47, fours: 4, sixes: 0 },
            { batsman_name: 'N. Curtis', how_out: 'b Wade', runs: 8, balls: 16, fours: 1, sixes: 0 },
            { batsman_name: 'J. Blackwell', how_out: 'c Hartley b Sutton', runs: 52, balls: 71, fours: 6, sixes: 0 },
            { batsman_name: 'R. Egan', how_out: 'lbw b Cross', runs: 21, balls: 30, fours: 2, sixes: 0 },
            { batsman_name: 'T. Bonner', how_out: 'c Nash b Sutton', runs: 15, balls: 22, fours: 1, sixes: 0 },
            { batsman_name: 'L. Finch', how_out: 'run out (Pearce)', runs: 18, balls: 27, fours: 2, sixes: 0 },
            { batsman_name: 'G. Holt', how_out: 'b Fletcher', runs: 9, balls: 13, fours: 1, sixes: 0 },
            { batsman_name: 'P. Ashe', how_out: 'c & b Cross', runs: 7, balls: 12, fours: 0, sixes: 0 },
            { batsman_name: 'M. Drew', how_out: 'b Wade', runs: 4, balls: 8, fours: 0, sixes: 0 },
            { batsman_name: 'C. Norris', how_out: 'b Sutton', runs: 2, balls: 5, fours: 0, sixes: 0 },
            { batsman_name: 'K. Iyer', how_out: 'not out', runs: 0, balls: 3, fours: 0, sixes: 0 },
          ],
          bowl: [
            { bowler_name: 'S. Fletcher', overs: '10', maidens: 2, runs: 32, wickets: 2, wides: 2, no_balls: 0 },
            { bowler_name: 'C. Wade', overs: '9', maidens: 1, runs: 28, wickets: 2, wides: 1, no_balls: 0 },
            { bowler_name: 'B. Sutton', overs: '10', maidens: 1, runs: 41, wickets: 3, wides: 3, no_balls: 2 },
            { bowler_name: 'D. Cross', overs: '9.2', maidens: 0, runs: 39, wickets: 2, wides: 1, no_balls: 0 },
            { bowler_name: 'O. Nash', overs: '5', maidens: 0, runs: 20, wickets: 0, wides: 1, no_balls: 0 },
          ],
        },
        {
          team_batting_id: 54532,
          team_batting_name: 'Sparsholt CC 1st XI',
          runs: 182,
          wickets: 4,
          overs: '38.1',
          declared: false,
          extras: { b: 2, lb: 3, w: 5, nb: 0, pen: 0, total: 10 },
          bat: [
            { batsman_name: 'J. Hartley', how_out: 'c Powell b Iyer', runs: 67, balls: 89, fours: 8, sixes: 1 },
            { batsman_name: 'T. Griffiths', how_out: 'b Norris', runs: 24, balls: 35, fours: 3, sixes: 0 },
            { batsman_name: 'W. Pearce', how_out: 'c Bonner b Drew', runs: 38, balls: 52, fours: 4, sixes: 0 },
            { batsman_name: 'O. Nash', how_out: 'run out (Holt)', runs: 11, balls: 18, fours: 1, sixes: 0 },
            { batsman_name: 'M. Gibson', how_out: 'not out', runs: 28, balls: 31, fours: 3, sixes: 1 },
            { batsman_name: 'B. Sutton', how_out: 'not out', runs: 9, balls: 12, fours: 1, sixes: 0 },
            { batsman_name: 'S. Fletcher', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'D. Cross', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'C. Wade', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'H. Frost', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'P. Carter', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
          ],
          bowl: [
            { bowler_name: 'K. Iyer', overs: '10', maidens: 1, runs: 42, wickets: 1, wides: 2, no_balls: 0 },
            { bowler_name: 'C. Norris', overs: '9', maidens: 0, runs: 38, wickets: 1, wides: 1, no_balls: 0 },
            { bowler_name: 'M. Drew', overs: '8', maidens: 0, runs: 35, wickets: 1, wides: 1, no_balls: 0 },
            { bowler_name: 'P. Ashe', overs: '7', maidens: 1, runs: 28, wickets: 0, wides: 0, no_balls: 0 },
            { bowler_name: 'G. Holt', overs: '4.1', maidens: 0, runs: 29, wickets: 0, wides: 1, no_balls: 0 },
          ],
        },
      ],
    }],
  },
  // Sparsholt 2nd XI lost to Eastleigh by 34 runs
  1007: {
    match_details: [{
      id: 1007,
      status: 'C',
      home_team_name: 'Eastleigh CC 2nd XI',
      away_team_name: 'Sparsholt CC 2nd XI',
      ground_name: 'Eastleigh Park',
      match_date: daysFromToday(-7),
      match_time: '13:00',
      result_description: 'Eastleigh CC won by 34 runs',
      innings: [
        {
          team_batting_id: 22007,
          team_batting_name: 'Eastleigh CC 2nd XI',
          runs: 179,
          wickets: 6,
          overs: '40.0',
          declared: false,
          extras: { b: 2, lb: 4, w: 10, nb: 0, pen: 0, total: 16 },
          bat: [
            { batsman_name: 'B. Osei', how_out: 'c Roberts b Hill', runs: 55, balls: 72, fours: 6, sixes: 1 },
            { batsman_name: 'T. Crane', how_out: 'b Hill', runs: 12, balls: 21, fours: 1, sixes: 0 },
            { batsman_name: 'D. Lyons', how_out: 'c Davies b Morton', runs: 38, balls: 49, fours: 4, sixes: 0 },
            { batsman_name: 'F. Singh', how_out: 'not out', runs: 41, balls: 53, fours: 5, sixes: 0 },
            { batsman_name: 'C. Hobbs', how_out: 'c Evans b Morton', runs: 14, balls: 19, fours: 2, sixes: 0 },
            { batsman_name: 'R. Watts', how_out: 'b Evans', runs: 7, balls: 11, fours: 0, sixes: 0 },
            { batsman_name: 'P. Ogden', how_out: 'not out', runs: 5, balls: 8, fours: 0, sixes: 0 },
            { batsman_name: 'M. Salter', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'A. Butt', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'G. Lamb', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'N. Page', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
          ],
          bowl: [
            { bowler_name: 'A. Hill', overs: '9', maidens: 1, runs: 32, wickets: 2, wides: 3, no_balls: 0 },
            { bowler_name: 'R. Morton', overs: '9', maidens: 0, runs: 38, wickets: 2, wides: 2, no_balls: 0 },
            { bowler_name: 'J. Evans', overs: '8', maidens: 0, runs: 35, wickets: 1, wides: 3, no_balls: 0 },
            { bowler_name: 'S. Roberts', overs: '8', maidens: 1, runs: 29, wickets: 0, wides: 1, no_balls: 0 },
            { bowler_name: 'K. Davies', overs: '6', maidens: 0, runs: 29, wickets: 0, wides: 1, no_balls: 0 },
          ],
        },
        {
          team_batting_id: 54533,
          team_batting_name: 'Sparsholt CC 2nd XI',
          runs: 145,
          wickets: 10,
          overs: '38.4',
          declared: false,
          extras: { b: 1, lb: 3, w: 7, nb: 0, pen: 0, total: 11 },
          bat: [
            { batsman_name: 'S. Roberts', how_out: 'c Osei b Page', runs: 31, balls: 44, fours: 3, sixes: 0 },
            { batsman_name: 'K. Davies', how_out: 'b Butt', runs: 8, balls: 15, fours: 1, sixes: 0 },
            { batsman_name: 'J. Evans', how_out: 'c Hobbs b Lamb', runs: 44, balls: 63, fours: 5, sixes: 0 },
            { batsman_name: 'R. Morton', how_out: 'b Page', runs: 17, balls: 26, fours: 2, sixes: 0 },
            { batsman_name: 'A. Hill', how_out: 'c Watts b Salter', runs: 19, balls: 28, fours: 2, sixes: 0 },
            { batsman_name: 'L. Brooks', how_out: 'b Lamb', runs: 6, balls: 11, fours: 0, sixes: 0 },
            { batsman_name: 'T. Manning', how_out: 'c Crane b Butt', runs: 4, balls: 9, fours: 0, sixes: 0 },
            { batsman_name: 'F. Owen', how_out: 'b Salter', runs: 7, balls: 13, fours: 1, sixes: 0 },
            { batsman_name: 'G. Price', how_out: 'not out', runs: 4, balls: 7, fours: 0, sixes: 0 },
            { batsman_name: 'D. Kemp', how_out: 'b Page', runs: 1, balls: 4, fours: 0, sixes: 0 },
            { batsman_name: 'H. Stone', how_out: 'b Butt', runs: 0, balls: 2, fours: 0, sixes: 0 },
          ],
          bowl: [
            { bowler_name: 'N. Page', overs: '9', maidens: 2, runs: 28, wickets: 3, wides: 2, no_balls: 0 },
            { bowler_name: 'A. Butt', overs: '8.4', maidens: 1, runs: 31, wickets: 3, wides: 1, no_balls: 0 },
            { bowler_name: 'G. Lamb', overs: '9', maidens: 0, runs: 36, wickets: 2, wides: 2, no_balls: 0 },
            { bowler_name: 'M. Salter', overs: '8', maidens: 0, runs: 32, wickets: 2, wides: 2, no_balls: 0 },
            { bowler_name: 'R. Watts', overs: '4', maidens: 0, runs: 18, wickets: 0, wides: 0, no_balls: 0 },
          ],
        },
      ],
    }],
  },
  // Sparsholt 3rd XI beat Otterbourne by 4 wkts
  1008: {
    match_details: [{
      id: 1008,
      status: 'C',
      home_team_name: 'Sparsholt CC 3rd XI',
      away_team_name: 'Otterbourne CC 3rd XI',
      ground_name: 'Sparsholt Village Ground',
      match_date: daysFromToday(-14),
      match_time: '13:00',
      result_description: 'Sparsholt CC won by 4 wickets',
      innings: [
        {
          team_batting_id: 22008,
          team_batting_name: 'Otterbourne CC 3rd XI',
          runs: 154,
          wickets: 8,
          overs: '40.0',
          declared: false,
          extras: { b: 3, lb: 5, w: 7, nb: 1, pen: 0, total: 16 },
          bat: [
            { batsman_name: 'P. Yates', how_out: 'c Barton b Long', runs: 28, balls: 39, fours: 3, sixes: 0 },
            { batsman_name: 'C. Munn', how_out: 'b Long', runs: 5, balls: 12, fours: 0, sixes: 0 },
            { batsman_name: 'E. Park', how_out: 'c Short b Bailey', runs: 47, balls: 65, fours: 5, sixes: 0 },
            { batsman_name: 'W. Ince', how_out: 'lbw b Graham', runs: 22, balls: 33, fours: 2, sixes: 0 },
            { batsman_name: 'J. Rees', how_out: 'c & b Bailey', runs: 18, balls: 25, fours: 2, sixes: 0 },
            { batsman_name: 'A. Bird', how_out: 'not out', runs: 15, balls: 21, fours: 1, sixes: 0 },
            { batsman_name: 'S. Hunt', how_out: 'b Long', runs: 8, balls: 14, fours: 1, sixes: 0 },
            { batsman_name: 'R. Ford', how_out: 'c Barton b Graham', runs: 3, balls: 7, fours: 0, sixes: 0 },
            { batsman_name: 'T. Goode', how_out: 'not out', runs: 2, balls: 5, fours: 0, sixes: 0 },
            { batsman_name: 'L. Ash', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'M. Fox', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
          ],
          bowl: [
            { bowler_name: 'N. Long', overs: '9', maidens: 1, runs: 28, wickets: 3, wides: 2, no_balls: 0 },
            { bowler_name: 'D. Bailey', overs: '9', maidens: 1, runs: 33, wickets: 2, wides: 2, no_balls: 0 },
            { bowler_name: 'I. Graham', overs: '9', maidens: 0, runs: 37, wickets: 2, wides: 2, no_balls: 1 },
            { bowler_name: 'C. Barton', overs: '8', maidens: 0, runs: 31, wickets: 0, wides: 1, no_balls: 0 },
            { bowler_name: 'F. Short', overs: '5', maidens: 0, runs: 18, wickets: 0, wides: 0, no_balls: 0 },
          ],
        },
        {
          team_batting_id: 54534,
          team_batting_name: 'Sparsholt CC 3rd XI',
          runs: 157,
          wickets: 6,
          overs: '34.2',
          declared: false,
          extras: { b: 1, lb: 2, w: 5, nb: 0, pen: 0, total: 8 },
          bat: [
            { batsman_name: 'C. Barton', how_out: 'c Yates b Fox', runs: 23, balls: 34, fours: 2, sixes: 0 },
            { batsman_name: 'F. Short', how_out: 'b Ash', runs: 11, balls: 18, fours: 1, sixes: 0 },
            { batsman_name: 'I. Graham', how_out: 'c Munn b Fox', runs: 52, balls: 68, fours: 6, sixes: 0 },
            { batsman_name: 'D. Bailey', how_out: 'b Goode', runs: 14, balls: 22, fours: 1, sixes: 0 },
            { batsman_name: 'N. Long', how_out: 'c Bird b Ash', runs: 29, balls: 38, fours: 3, sixes: 0 },
            { batsman_name: 'A. West', how_out: 'c Ford b Goode', runs: 9, balls: 14, fours: 1, sixes: 0 },
            { batsman_name: 'R. Haines', how_out: 'not out', runs: 14, balls: 17, fours: 2, sixes: 0 },
            { batsman_name: 'T. Moon', how_out: 'not out', runs: 3, balls: 5, fours: 0, sixes: 0 },
            { batsman_name: 'S. Prior', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'K. Lamb', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
            { batsman_name: 'B. Norris', how_out: 'did not bat', runs: null, balls: null, fours: null, sixes: null },
          ],
          bowl: [
            { bowler_name: 'M. Fox', overs: '8', maidens: 1, runs: 33, wickets: 2, wides: 1, no_balls: 0 },
            { bowler_name: 'L. Ash', overs: '8', maidens: 0, runs: 36, wickets: 2, wides: 2, no_balls: 0 },
            { bowler_name: 'T. Goode', overs: '7', maidens: 0, runs: 31, wickets: 2, wides: 1, no_balls: 0 },
            { bowler_name: 'R. Ford', overs: '7', maidens: 1, runs: 28, wickets: 0, wides: 1, no_balls: 0 },
            { bowler_name: 'S. Hunt', overs: '4.2', maidens: 0, runs: 21, wickets: 0, wides: 0, no_balls: 0 },
          ],
        },
      ],
    }],
  },
};
