services:
  - type: web
    name: sparsholt-cricket
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYCRICKET_API_TOKEN
        sync: false
